### ISSUE TITLE
It only gets master if its name is "mymaster"

### ISSUE THREAD

**Issue by alanwillms** [pyurin/yii2-redis-ha#1]
See this: https://github.com/pyurin/yii2-redis-ha/blob/master/src/SentinelConnection.php#L55

I am working with a master database called "another-name-master", so this extension simply doesn't work.

**Comment by pyurin** [comment]
Yes, it was rather silly of me. Fixed.

**Comment by alanwillms** [comment]
thanks @pyurin !
