### ISSUE TITLE
I hope it can support separating write/read

### ISSUE THREAD

**Issue by asaarashi** [pyurin/yii2-redis-ha#2]
I hope it can support separating write/read. When writing, it accesses the master, and when reading it accesses a slave.

**Comment by pyurin** [comment]
Hi. 
I think I understand why you want it, but it seems to be a dangerous idea.
The main aim of the project is HA - not load balancing. And also don`t forget that replication has a lag, so if I do those commands sequentially
$redis->set('test_key', 1);
$redis->set('test_key', 2);
$redis->get('test_key');
will not give 2 and that would be surprising.
Do have any practical arguments to separate read/writes in your projects?

**Comment by asaarashi** [comment]
Hi pyurin,
Thanks for quick reply. 
My scene is processing a large number of data rows(>100 rows/1s) and every row needs to get information from Redis, and there are still some read requests from Web at the same time. I just want to reduce the master's pressure.
I did not know the replication's bug you said, so you may be right. But I don't know what's the best practice for this scene. Appreciate if you can give me some suggestions. :)
Sorry for my poor English.

**Comment by pyurin** [comment]
That`s not replication bug, it`s replication lag) that means delay. Separating read/writes to different servers will give you more complicity then performance boost I suppose.
1 redis instance will easily handle 1k rps - check out that benchmark
http://skipperkongen.dk/2013/08/27/how-many-requests-per-second-can-i-get-out-of-redis/
You can contact me over skype: p.yurin

**Comment by asaarashi** [comment]
Thank you! Sorry, I didn't notice your reply.
