### ISSUE TITLE
Error in Helper::executeCommand for commands with space inside (i.e. CLIENT LIST)

### ISSUE THREAD

**Issue by zukk** [pyurin/yii2-redis-ha#3]
> array_unshift($params, $name); 

at line 14 must be changed to 

> $params = array_merge(explode(' ', $name), $params);

because two word commands is not processing correctly and causes error like 
'Redis error: ERR unknown command 'CLIENT LIST'

**Comment by pyurin** [comment]
Thank you, I've merged your request
