### ISSUE TITLE
Packagist don't see v1.1.7

### ISSUE THREAD

**Issue by DmLapin** [pyurin/yii2-redis-ha#6]
Packagist can't fetch version 1.1.7. composer.json contains old `"version" : "1.1.6"`: https://github.com/pyurin/yii2-redis-ha/blob/1.1.7/composer.json.

**Comment by pyurin** [comment]
Can you help me to fix it?

**Comment by pyurin** [comment]
Fixed it finally. Thanks for reporting

**Comment by DmLapin** [comment]
Thank you 👍
